[package]
name = "pizr"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = "1.8.0"
zbus = "5.1.1"
tokio = { version = "1.42.0", features = ["rt", "rt-multi-thread", "macros", "time"] }
regex = "1.12.2"
